# -*- coding: utf-8 -*-
"""
/***************************************************************************
 classnome
                                 A QGIS plugin
 descricao
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-05
        copyright            : (C) 2025 by Rodolfo Martins de Carvalho
        email                : rodolfomartins09@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

def classFactory(iface):  # pylint: disable=invalid-name
    """Load classnome class from file classnome.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .principal import classnome
    return classnome(iface)
